#' Function to preserve the experiment
#'
#' This function allows you to preserve the experiment, detecting new installed applications
#' and creating a relational database to store provenance information
#' @param con Connection to the porvenance database
#' @param prov_json Location of the prov.json file generated by the validate function
#' @keywords preserve, provenance
#' @export
#' @examples
#' preserve()
#' preserve(con = '~/prov.db', prov_json = '~/prov.json')

preserve <- function(con = '~/prov.db', prov_json = '~/Dropbox/Artigos/2019/ER/experiment/modelr/prov_script/prov.json'){
  # Vagrant
  # system('apt list --installed > ~/.new_installed.log; diff ~/.installed.log ~/.new_installed.log > ~/.diff.log')
  # diff <- read.csv('~/.diff.log', sep = " ", header = F)
  # diff <- diff[diff$V5 == '[installed]',]
  # diff <- diff[,2]
  # packages <- gsub("\\/.*","",diff)
  # packages <- paste('apt install -y ', packages, sep = "")
  #
  # vagrant_file <- readLines(con = '/vagrant/Vagrantfile')
  # end_vagrant_file = which(vagrant_file == "  SHELL")
  # for (p in 1:length(packages)){
  #   vagrant_file[end_vagrant_file] <- packages[p]
  #   end_vagrant_file = end_vagrant_file + 1
  # }
  # vagrant_file[end_vagrant_file] <- "  SHELL"
  # vagrant_file[end_vagrant_file+1] <- "end"
  # writeLines(vagrant_file, con = '~/Vagrantfile')

  # Create db
  library(sqldf); library(DBI)
  db <- dbConnect(SQLite(), dbname=con)
  #dbSendQueries(db, sqlFromFile("db_schema.sql"))
  # Import info to db
  parserDB(db, prov_json)
  print('Finished')
}
